export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Footer} from './Footer'
export {default as MessageForm} from './MessageForm'
export {default as Family} from './Family'
export {default as Portfolio} from './Portfolio'
